### ISSUE TITLE
100% zoomed vs 90% zoomed out, the carousell cards not resize accordingly

### ISSUE THREAD

**Issue by davidwang98** [ong6/brand3d#12]
![image](https://user-images.githubusercontent.com/71161461/152664831-38e477a8-ab24-456d-9e7d-5c6e566360a3.png)
![image](https://user-images.githubusercontent.com/71161461/152664849-945c22cc-8508-4d93-8097-c85569aac13a.png)

**Comment by ong6** [comment]
Prolly cause i used view height.

**Comment by ong6** [comment]
fixed
